### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by celsomiranda** [hexojs/hexo-browsersync#7]
This is what I get using latest versions of `hexo`, `hexo-server` and `hexo-browsersync`.
``` node
D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\lib\browsersync.js:32
      return ~res.getHeader('Content-Type').indexOf('text/html');
                                           ^
TypeError: Cannot read property 'indexOf' of undefined
    at Object.when (D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\lib\browsersync.js:32:44)
    at D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\node_modules\connect-injector\lib\connect-injector.js:47:21
    at Function._.each._.forEach (D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\node_modules\connect-injector\node_modules\underscore\underscore.js:153:9)
    at ServerResponse.mixin._interceptCheck (D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\node_modules\connect-injector\lib\connect-injector.js:46:13)
    at ServerResponse.mixin.end (D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\node_modules\connect-injector\lib\connect-injector.js:103:19)
    at ServerResponse.self.(anonymous function) (D:\Repos\celsomiranda.github.io\node_modules\hexo-browsersync\node_modules\connect-injector\node_modules\uberproto\lib\proto.js:61:21)
    at ServerResponse.res.end (D:\Repos\celsomiranda.github.io\node_modules\hexo-server\node_modules\compression\index.js:97:20)
    at SendStream.notModified (D:\Repos\celsomiranda.github.io\node_modules\hexo-server\node_modules\serve-static\node_modules\send\index.js:309:7)
    at SendStream.send (D:\Repos\celsomiranda.github.io\node_modules\hexo-server\node_modules\serve-static\node_modules\send\index.js:516:17)
    at onstat (D:\Repos\celsomiranda.github.io\node_modules\hexo-server\node_modules\serve-static\node_modules\send\index.js:600:10)
    at FSReqWrap.oncomplete (fs.js:78:15)
```

**Comment by celsomiranda** [comment]
Got the fix from: https://github.com/schmich/connect-browser-sync/blob/master/index.js#L15
